export const RULES={width:1280,playerHp:100,bossHp:240,speed:330,cooldown:2.8,range:660,meleeRange:250};
export function createState(){return{phase:'ready',time:0,p:{x:280,hp:100,inv:0},b:{x:960,hp:240,hit:0,dir:-1},cooldown:0,attack:null,nextAttack:1.7,turn:0,ult:null,events:[],hits:0,casts:0,damageTaken:0};}
export function start(s){Object.assign(s,createState());s.phase='playing';return s;}
function event(s,type,extra={}){s.events.push({type,...extra});}
export function ultimate(s,mode='laser'){if(s.phase!=='playing'||s.cooldown>0)return false;s.cooldown=RULES.cooldown;s.casts++;const dir=Math.sign(s.b.x-s.p.x)||1,dist=Math.abs(s.b.x-s.p.x),melee=mode==='sword',hit=dist<=(melee?RULES.meleeRange:RULES.range);s.ult={time:0,dir,x:s.p.x,hit,melee};if(hit){const damage=melee?64:42;s.b.hp=Math.max(0,s.b.hp-damage);s.b.hit=.45;s.hits++;event(s,'hit',{damage,x:s.b.x,melee});if(s.b.hp===0){s.phase='won';s.attack=null;event(s,'won');}}else event(s,'miss');event(s,'ultimate',{hit,melee});return true;}
function hurt(s,damage){if(s.p.inv>0||s.phase!=='playing')return;s.p.hp=Math.max(0,s.p.hp-damage);s.p.inv=.85;s.damageTaken+=damage;event(s,'hurt',{damage,x:s.p.x});if(!s.p.hp){s.phase='lost';s.attack=null;event(s,'lost');}}
export function step(s,dt,move=0){dt=Math.min(.05,Math.max(0,dt));if(s.phase!=='playing')return;s.time+=dt;s.p.x=Math.max(95,Math.min(1185,s.p.x+Math.sign(move)*RULES.speed*dt));s.p.inv=Math.max(0,s.p.inv-dt);s.b.hit=Math.max(0,s.b.hit-dt);s.cooldown=Math.max(0,s.cooldown-dt);if(s.ult){s.ult.time+=dt;if(s.ult.time>.8)s.ult=null;}if(s.attack){const a=s.attack;a.t+=dt;if(a.t>=a.warn&&!a.struck){a.struck=true;if(a.type==='dash'){a.from=s.b.x;a.to=Math.max(120,Math.min(1160,a.target));}else{if(Math.abs(s.p.x-a.target)<92)hurt(s,15);event(s,'impact',{x:a.target,attackType:'acid'});}}
 if(a.type==='dash'&&a.struck){const t=Math.min(1,(a.t-a.warn)/.36);s.b.x=a.from+(a.to-a.from)*(1-(1-t)**3);if(!a.connected&&Math.abs(s.p.x-s.b.x)<142){hurt(s,23);a.connected=true;event(s,'impact',{x:s.b.x,attackType:'dash'});}}
 if(a.t>a.warn+.65){s.attack=null;s.nextAttack=s.b.hp<100?1.05:1.55;}}
 else{s.nextAttack-=dt;const d=s.p.x-s.b.x;if(Math.abs(d)>330)s.b.x+=Math.sign(d)*(s.b.hp<100?65:42)*dt;if(s.nextAttack<=0){s.turn++;const type=s.turn%3===0?'dash':'acid';s.attack={type,t:0,warn:type==='dash'?1.0:1.05,target:s.p.x,from:s.b.x,struck:false,connected:false};event(s,'warning',{attack:type});}}
 s.b.x=Math.max(100,Math.min(1180,s.b.x));}
