import{RULES,createState,start,ultimate,step}from'./engine.js';
const sin=Math.sin;
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),state=createState();let loaded=false,keys=new Set(),last=0,visualTime=0,fx=[],shake=0,soundOn=false,audio,captionTime=0,viewW=1280;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const doctor=new Image(),boss=new Image();doctor.src='assets/doctor.png';boss.src='assets/academician.png';
Promise.all([doctor.decode(),boss.decode()]).then(()=>{loaded=true;$('#start').disabled=false;$('#startLabel').textContent='开始对决';}).catch(()=>{$('#startLabel').textContent='重新载入角色';$('#dialogText').textContent='角色素材未能载入，请重试。';$('#start').disabled=false;$('#start').onclick=()=>location.reload();});
function tone(f,d=.15,type='sine',vol=.05,end=f){if(!soundOn)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),audio.currentTime+d);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch{}}
function say(text,d=1.7){$('#caption').textContent=text;captionTime=d;$('#caption').classList.add('show');}
function begin(){if(!loaded)return;start(state);keys.clear();fx=[];$('#overlay').classList.add('hidden');$('#pause').disabled=false;$('#pause').innerHTML='暂停 <span>Ⅱ</span>';say('保持移动，避开预警');tone(440,.16,'sine',.04,660);sync();}
function pause(){if(!['playing','paused'].includes(state.phase))return;if(state.phase==='playing'){state.phase='paused';keys.clear();showModal('PAUSED','稍作停留。','战斗已暂停，准备好就继续。','继续对决');$('#pause').innerHTML='继续 <span>▷</span>';}else{state.phase='playing';$('#overlay').classList.add('hidden');$('#pause').innerHTML='暂停 <span>Ⅱ</span>';}}
function showModal(eye,title,desc,button){$('#eyebrow').textContent=eye;$('#dialogTitle').innerHTML=title;$('#dialogText').textContent=desc;$('#startLabel').textContent=button;$('#startNote').textContent=state.phase==='paused'?'暂停期间不会受到伤害':'← → 移动 · 空格释放大招';$('#overlay').classList.remove('hidden');}
$('#start').addEventListener('click',()=>state.phase==='paused'?pause():begin());$('#pause').onclick=pause;
$('#sound').onclick=()=>{soundOn=!soundOn;$('#soundText').textContent=soundOn?'开':'关';$('#sound').setAttribute('aria-pressed',String(soundOn));$('#sound').setAttribute('aria-label',soundOn?'关闭音效':'开启音效');tone(600,.1);};
function cast(){if(!ultimate(state)){if(state.phase==='playing'&&state.cooldown>0)say(`大招冷却 · ${state.cooldown.toFixed(1)} 秒`,.7);return;}consume();sync();}
$('#ultimate').onclick=cast;
addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Space'].includes(e.code))return;if(e.target instanceof HTMLButtonElement&&e.code==='Space'&&state.phase!=='playing')return;e.preventDefault();if(e.code==='Space'){if(!e.repeat){if(state.phase==='ready')begin();else cast();}}else if(state.phase==='playing')keys.add(e.code);});
addEventListener('keyup',e=>{keys.delete(e.code);});addEventListener('blur',()=>{keys.clear();if(state.phase==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.phase==='playing')pause();});
for(const[id,code]of[['left','ArrowLeft'],['right','ArrowRight']]){const el=$('#'+id);el.addEventListener('pointerdown',e=>{if(state.phase!=='playing')return;e.preventDefault();el.setPointerCapture(e.pointerId);keys.add(code);el.classList.add('active');});for(const name of['pointerup','pointercancel','lostpointercapture'])el.addEventListener(name,()=>{keys.delete(code);el.classList.remove('active');});}
function consume(){for(const e of state.events.splice(0)){if(e.type==='ultimate'){tone(160,.48,'sawtooth',.035,55);shake=reduced?0:6;say(e.melee?'光炮命中 · 光剑追击':e.hit?'光炮命中！':'距离太远，靠近后再出招');}if(e.type==='hit'){fx.push({kind:'text',x:e.x,y:265,t:0,life:1,text:'−'+e.damage,color:'#b8fff1'});burst(e.x,360,26,'#88eee7');}if(e.type==='hurt'){tone(95,.25,'triangle',.08,35);shake=reduced?0:8;fx.push({kind:'text',x:e.x,y:250,t:0,life:1,text:'−'+e.damage,color:'#ffab93'});burst(e.x,380,17,'#ff9f81');}if(e.type==='impact')burst(e.x,465,22,'#e8ac7c');if(e.type==='warning'){say(e.attack==='dash'?'院士蓄力冲撞 · 远离标记位置':'酸液来袭 · 移开红色预警区',1.3);tone(320,.13,'sine',.03,280);}if(e.type==='won'){keys.clear();tone(440,.5,'triangle',.05,880);setTimeout(()=>{if(state.phase!=='won')return;showModal('VICTORY · 胜利','博士，胜出。',`${Math.ceil(state.time)} 秒结束对决 · ${state.hits} 次大招命中 · 剩余 ${state.p.hp} 生命`,'再战一局');$('#pause').disabled=true;},850);}if(e.type==='lost'){keys.clear();tone(160,.65,'triangle',.05,40);setTimeout(()=>{if(state.phase!=='lost')return;showModal('DEFEAT · 败北','再找一个破绽。','先避开红色预警，再靠近释放大招。近身时会追加光剑伤害。','再战一局');$('#pause').disabled=true;},500);}}}
function burst(x,y,n,color){for(let i=0;i<n;i++)fx.push({kind:'particle',x,y,vx:(Math.random()-.5)*350,vy:(Math.random()-.6)*270,t:0,life:.35+Math.random()*.5,color});}
function sync(){const p=Math.ceil(state.p.hp),b=Math.ceil(state.b.hp);$('#playerNumbers').innerHTML=p+' <small>/ 100</small>';$('#bossNumbers').innerHTML=b+' <small>/ 240</small>';$('#playerHealth i').style.width=p+'%';$('#bossHealth i').style.width=b/240*100+'%';$('#playerHealth').setAttribute('aria-valuenow',p);$('#bossHealth').setAttribute('aria-valuenow',b);$('#timer').textContent=`${Math.floor(state.time/60).toString().padStart(2,'0')}:${Math.floor(state.time%60).toString().padStart(2,'0')}`;$('#ultimate').disabled=state.phase!=='playing'||state.cooldown>0;$('#ultLabel').textContent=state.cooldown>0?'能量恢复中':'大招就绪';$('#cooldownText').textContent=state.cooldown>0?state.cooldown.toFixed(1)+' 秒':'READY ↗';$('#cooldownFill').style.width=(1-state.cooldown/RULES.cooldown)*100+'%';for(const[id,key]of[['left','ArrowLeft'],['right','ArrowRight']])$('#'+id).classList.toggle('active',keys.has(key));}
function glow(x,y,r,c){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,c);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);}
function sprite(img,x,y,size,flip=false,alpha=1,tilt=0){if(!img.complete||!img.naturalWidth)return;ctx.save();ctx.translate(x,y);ctx.rotate(tilt);ctx.scale(flip?-1:1,1);ctx.globalAlpha=alpha;ctx.drawImage(img,-size/2,-size/2,size,size);ctx.restore();}
function draw(){const cw=canvas.width,ch=canvas.height;ctx.clearRect(0,0,cw,ch);ctx.fillStyle='#192631';ctx.fillRect(0,0,cw,ch);ctx.save();const rect=canvas.getBoundingClientRect(),mobile=rect.width<600,px0=state.phase==='ready'?635:state.p.x,bx0=state.phase==='ready'?1000:state.b.x,vw=mobile?Math.max(780,Math.min(1280,Math.abs(px0-bx0)+420)):1280,scale=mobile?cw/vw:Math.min(cw/1280,ch/640),center=mobile?Math.max(vw/2,Math.min(1280-vw/2,(px0+bx0)/2)):640;ctx.translate(cw/2-center*scale,mobile?ch*.60-350*scale:ch/2-320*scale);ctx.scale(scale,scale);const grad=ctx.createLinearGradient(0,0,0,640);grad.addColorStop(0,'#15202b');grad.addColorStop(1,'#202f3b');ctx.fillStyle=grad;ctx.fillRect(0,0,1280,640);glow(410,390,380,'#2c77882a');glow(1000,410,320,'#ad683024');
ctx.strokeStyle='#8ab5c00b';ctx.lineWidth=1;for(let x=0;x<=1280;x+=80){ctx.beginPath();ctx.moveTo(x,140);ctx.lineTo(x,545);ctx.stroke();}for(let y=160;y<=545;y+=65){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1280,y);ctx.stroke();}ctx.strokeStyle='#accddb27';ctx.beginPath();ctx.moveTo(0,520);ctx.lineTo(1280,520);ctx.stroke();ctx.fillStyle='#0e192644';ctx.fillRect(0,521,1280,119);
for(let i=0;i<35;i++){const x=(i*139.13-visualTime*(7+i%3*5)+2560)%1280,y=155+(i*67.9)%330;ctx.fillStyle=i%2?'#b7d5db44':'#a9a09433';ctx.fillRect(x,y,1.4,1.4);}ctx.font='700 146px sans-serif';ctx.fillStyle='#c5dde903';ctx.textAlign='center';ctx.fillText('博士  VS  院士',650,430);
if(shake>0)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);const ready=state.phase==='ready';let px=ready?635:state.p.x,bx=ready?1000:state.b.x;const py=350+sin(visualTime*2.7)*5,by=407+sin(visualTime*1.7)*3;const face=bx>=px;const a=state.attack;
if(a){const r=a.type==='dash'?145:92;const t=Math.min(1,a.t/a.warn);ctx.save();ctx.translate(a.target,506);ctx.scale(1,.25);ctx.fillStyle=a.struck?'#fd8e6550':'#fc906327';ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffb192';ctx.lineWidth=5;ctx.setLineDash([15,10]);ctx.beginPath();ctx.arc(0,0,r*t,0,Math.PI*2);ctx.stroke();ctx.restore();if(!a.struck){ctx.fillStyle='#ffbda0';ctx.font='600 15px sans-serif';ctx.textAlign='center';ctx.fillText(a.type==='dash'?'冲撞区域':'酸液落点',a.target,549);if(a.type==='acid'){const t=Math.max(0,Math.min(1,a.t/a.warn)),x=a.from+(a.target-a.from)*t,y=380-170*sin(t*Math.PI)+95*t;glow(x,y,30,'#c5dd8655');ctx.fillStyle='#d8e88e';ctx.beginPath();ctx.arc(x,y,9,0,Math.PI*2);ctx.fill();}}}
glow(px,493,80,'#63eeed17');ctx.save();ctx.translate(px,500);ctx.scale(1,.1);ctx.fillStyle='#01080c66';ctx.beginPath();ctx.arc(0,0,110,0,Math.PI*2);ctx.fill();ctx.restore();
let bossAlpha=state.phase==='won'?Math.max(.08,1-(visualTime-(window.winVisual||visualTime))*2):1;if(state.phase==='won'&&!window.winVisual)window.winVisual=visualTime;if(state.phase!=='won')window.winVisual=0;
sprite(boss,bx,by,ready?280:310,bx<px,bossAlpha,state.b.hit>0?sin(state.b.hit*40)*.03:0);if(state.b.hit>0)glow(bx,360,100,'#feaa7044');sprite(doctor,px,py,ready?455:400,!face,state.p.inv>0&&Math.floor(visualTime*16)%2?.45:1,keys.size?(face?.025:-.025):0);
const coreX=px+(face?27:-27),coreY=py-18;glow(coreX,coreY,24,'#70e6ff60');ctx.fillStyle='#d6fdff';ctx.beginPath();ctx.arc(coreX,coreY,3,0,Math.PI*2);ctx.fill();
if(state.ult){const u=state.ult,t=u.time,alpha=Math.max(0,1-t/.72);ctx.save();ctx.globalAlpha=alpha;const endX=u.x+u.dir*RULES.range;ctx.shadowColor='#78f8ff';ctx.shadowBlur=22;for(const[w,c]of[[28,'#6ecbe622'],[10,'#72ddeb'],[3,'#edfffb']]){ctx.strokeStyle=c;ctx.lineWidth=w;ctx.beginPath();ctx.moveTo(u.x+u.dir*27,coreY);ctx.lineTo(Math.max(0,Math.min(1280,endX)),coreY);ctx.stroke();}glow(u.x+u.dir*27,coreY,75,'#a4f8ff70');ctx.restore();if(u.melee)drawSword(u,px,py);}
for(const f of fx){ctx.globalAlpha=Math.max(0,1-f.t/f.life);ctx.fillStyle=f.color;if(f.kind==='particle'){ctx.fillRect(f.x,f.y,4,4);}else{ctx.font='800 34px sans-serif';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y-f.t*65);}}ctx.globalAlpha=1;ctx.restore();}
// A mirrored arm-and-blade swing, anchored to the pilot's hand.
function drawSword(u,x,y){
 const t=u.time;if(t<.10)return;
 const progress=Math.min(1,(t-.10)/.53),ease=1-Math.pow(1-progress,3);
 const angle=reduced?.25:-1.65+ease*3.05;
 const opacity=Math.min(1,(t-.10)*18)*Math.min(1,(.8-t)*9);
 ctx.save();ctx.translate(x,y);ctx.scale(u.dir,1);ctx.globalAlpha=Math.max(0,opacity);
 // The armored forearm follows the blade through the slash.
 ctx.translate(57,8);ctx.rotate(angle);
 ctx.lineCap='round';ctx.strokeStyle='#101b29';ctx.lineWidth=24;
 ctx.beginPath();ctx.moveTo(-35,8);ctx.lineTo(15,0);ctx.stroke();
 ctx.strokeStyle='#e5edf0';ctx.lineWidth=16;ctx.stroke();
 ctx.fillStyle='#233f60';ctx.fillRect(2,-12,28,24);
 ctx.shadowColor='#70faff';ctx.shadowBlur=25;
 // Several trailing edges form a broad crescent rather than a single ring.
 if(progress>.08){for(let i=0;i<9;i++){
 ctx.strokeStyle=`rgba(92,238,255,${(1-i/9)*.24})`;ctx.lineWidth=19-i*1.7;
 ctx.beginPath();ctx.arc(0,0,200-i*3,-Math.min(1.2,progress*2.1)-i*.018,0);ctx.stroke();
 }}
 for(const[w,c]of[[25,'#45d9ff33'],[12,'#63efff'],[4,'#f2ffff']]){
 ctx.strokeStyle=c;ctx.lineWidth=w;ctx.beginPath();ctx.moveTo(36,0);ctx.lineTo(220,0);ctx.stroke();}
 ctx.shadowBlur=0;ctx.fillStyle='#eacb80';ctx.fillRect(25,-20,9,40);
 ctx.fillStyle='#182f46';ctx.fillRect(4,-6,22,12);
 ctx.fillStyle='#f5e3ac';ctx.fillRect(1,-9,7,18);ctx.restore();
 // Brief impact rays make contact readable even during the fast swing.
 if(t>.22&&t<.52){const fade=1-(t-.22)/.3;ctx.save();ctx.globalAlpha=fade;
 ctx.translate(state.b.x,365);ctx.strokeStyle='#e5ffff';ctx.shadowColor='#57eaff';ctx.shadowBlur=18;
 for(let i=0;i<10;i++){const a=i*Math.PI/5+.2,r=35+(1-fade)*65;ctx.lineWidth=i%2?2:4;
 ctx.beginPath();ctx.moveTo(Math.cos(a)*20,Math.sin(a)*20);ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r);ctx.stroke();}
 ctx.restore();}
}
function frame(now){const dt=Math.min(.04,(now-last)/1000||0);last=now;if(state.phase!=='paused'){visualTime+=dt;if(state.phase==='won'&&state.ult){state.ult.time+=dt;if(state.ult.time>.8)state.ult=null;}step(state,dt,(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0));consume();for(const f of fx){f.t+=dt;if(f.kind==='particle'){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=180*dt;}}fx=fx.filter(f=>f.t<f.life);shake=Math.max(0,shake-dt*30);captionTime-=dt;if(captionTime<=0)$('#caption').classList.remove('show');}sync();draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
// Keep the complete battlefield visible at narrow widths.
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);}new ResizeObserver(resize).observe(canvas);
const mc=document.modelContext;if(mc?.registerTool){const ctrl=new AbortController();const tools=[{name:'get_battle_status',description:'Read the current battle state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({phase:state.phase,playerHp:state.p.hp,bossHp:state.b.hp,cooldown:Math.round(state.cooldown*10)/10,time:Math.round(state.time)})},{name:'start_battle',description:'Start or restart the visible battle.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(!loaded)throw Error('Characters are not ready');begin();return{phase:state.phase};}}];for(const tool of tools){const run=tool.execute;tool.execute=(input={})=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No arguments expected');return run();};try{Promise.resolve(mc.registerTool(tool,{signal:ctrl.signal})).catch(()=>{});}catch{}}addEventListener('pagehide',()=>ctrl.abort(),{once:true});}
